version: "3"
services:
  frontend:
    build: user-list-app-frontend
    ports: 
      - "8080:8080"
    links:
      - backend
  backend:
    build: user-list-app-backend
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"